# Config Version - 2
telegram:

  botToken: "ВАШ_TELEGRAM_BOT_TOKEN"

  chatId: ""

# supports: en, ru, ua, kz, es, ar
language: "ru"

telegram-to-minecraft-format: "[TG] {sender}: {message}"
minecraft-to-telegram-format: "[MC] {sender}: {message}"

check-for-updates: true
