# Config Version - 2
telegram:

  botToken: "TELEGRAM_BOT_TOKEN"

# supports: en, ru, ua, kz, es, ar
language: "en"

telegram-to-minecraft-format: "[TG] {sender}: {message}"
minecraft-to-telegram-format: "[MC] {sender}: {message}"

check-for-updates: true
