name: TG2Nukkit
version: 1.2.1
main: com.debianrose.Main
api: ["1.0.0"]
author: desharish
description: Bridge Between Telegram And Nukkit
commands:
  setlanguage:
    description: Change the plugin language.
    usage: /setlanguage <ru|en|es|ua|kz|ar>
    permission: op
permissions:
  telegrambridge.setlanguage:
    description: Allows changing the plugin language.
    default: op
