name: Publish Plugin With Maven

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }} 
        asset_path: target/tg2nukkit-${{ github.event.release.tag_name }}.jar  
        asset_name: tg2nukkit-${{ github.event.release.tag_name }}.jar  # Имя файла в релизе
        asset_content_type: application/java-archive 