name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Verify JAR file exists
        id: verify_jar
        run: |
          if [ -f "target/tg2nukkit-1.2.jar" ]; then
            echo "JAR file found: target/tg2nukkit-1.2.jar"
            echo "JAR_PATH=target/tg2nukkit-1.2.jar" >> $GITHUB_ENV
          else
            echo "JAR file not found!"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TG2Nukkit
          path: ${{ env.JAR_PATH }}

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.JAR_PATH }}
          asset_name: tg2nukkit-1.2.jar
          asset_content_type: application/java-archive

      - name: Clean up target directory
        run: rm -rf target